### ISSUE TITLE
Many coach images are blurry 

### ISSUE THREAD

**Issue by ericchen0121** [dbc-coaches/public#19]
Update the gravatar images urls to use a consistent "s=xxx" parameter grabbing a sharp image size. 

Some are s=200, others s=99 (ie. will download a 200x200 image and then resize it to 100x100). 
When s=99, images are blurry.

You'll probably also want to balance this with not increasing the page weight too much to make the page load slowly (ie, don't do s=400, find the right balance of image clarity and smallest download image size).

**Comment by SamSamskies** [comment]
If we start using templates (https://github.com/dbc-coaches/public/issues/17), this won't be a problem anymore. The inconsistency part of the problem at least.

**Comment by jonathanpeterwu** [comment]
awesome thanks for the update - we're gonna automate pulling in poeple pictures etc from github, should update the resolution

**Comment by jonathanpeterwu** [comment]
temporary fix update res on all imgs. 
[PR to fix it ](https://github.com/dbc-coaches/public/pull/21)
